version: '3.8'

services:
  # GPT Researcher Core
  gpt-researcher:
    build:
      context: .
      dockerfile: Dockerfile.gpt-researcher
    container_name: gpt-researcher-enhanced
    ports:
      - "8068:8000"  # Enhanced stack uses 8068-8077 range
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RESEARCH_TYPE=${RESEARCH_TYPE:-research_report}
      - MAX_ITERATIONS=${MAX_ITERATIONS:-3}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - gpt-researcher-enhanced

  # Legal Document Enhancement
  legal-enhancement:
    build:
      context: .
      dockerfile: Dockerfile.legal-enhancement
    container_name: legal-enhancement-enhanced
    ports:
      - "8069:8001"  # Enhanced stack uses 8068-8077 range
    volumes:
      - ./legal_document_enhancement:/app/legal_document_enhancement
      - ./gpt_researcher:/app/gpt_researcher
      - ./backend:/app/backend
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_ENHANCED_PROCESSING=${USE_ENHANCED_PROCESSING:-true}
      - USE_SEMANTIC_CHUNKING=${USE_SEMANTIC_CHUNKING:-true}
      - EMBED_MODEL_NAME=${EMBED_MODEL_NAME:-BAAI/bge-large-en-v1.5}
      - SIMILARITY_THRESHOLD=${SIMILARITY_THRESHOLD:-0.75}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - gpt-researcher-enhanced

networks:
  gpt-researcher-enhanced:
    driver: bridge
    name: gpt-researcher-enhanced