version: '3.8'

services:
  # GPT Researcher Core (Basic)
  gpt-researcher:
    build:
      context: .
      dockerfile: Dockerfile.gpt-researcher
    container_name: gpt-researcher-basic
    ports:
      - "8067:8000"  # Basic stack uses original GPT Researcher port
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RESEARCH_TYPE=${RESEARCH_TYPE:-research_report}
      - MAX_ITERATIONS=${MAX_ITERATIONS:-3}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - gpt-researcher-basic

networks:
  gpt-researcher-basic:
    driver: bridge
    name: gpt-researcher-basic