version: '3.8'

services:
  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-basic
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - gpt-researcher-basic

  # GPT Researcher Core (Basic)
  gpt-researcher:
    build:
      context: .
      dockerfile: Dockerfile.gpt-researcher
    container_name: gpt-researcher-basic
    ports:
      - "8067:8000"  # Basic stack uses original GPT Researcher port
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - OPENAI_API_KEY=ollama
      - OPENAI_API_BASE_URL=http://ollama:11434/v1
      - OLLAMA_BASE_URL=http://ollama:11434
      - LANGCHAIN_API_KEY=
      - TAVILY_API_KEY=
      - RESEARCH_TYPE=research_report
      - MAX_ITERATIONS=3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - gpt-researcher-basic
    depends_on:
      - ollama

volumes:
  ollama_data:

networks:
  gpt-researcher-basic:
    driver: bridge
    name: gpt-researcher-basic